feat: filter list
ildaneta/make-crypto-mobile-hackathon pull request #16
Opened 2021-11-14 20:49 UTC by huduarte

- adding filter list component
- adding filter button component
- adding neutralColor 0 component

2021-11-14 21:58 UTC, ildaneta requested changes

2021-11-14 21:58 UTC, ildaneta commented on Project_Name/codebase/src/components/FilterList/index.tsx
> +  setCategory: (tagKey: string) => void;
Nesse caso o nome da prop seria filterKey?

2021-11-14 21:58 UTC, ildaneta commented on Project_Name/codebase/src/components/FilterList/index.tsx
> +  tags,
Aqui seria filters

2021-11-14 21:58 UTC, ildaneta commented on Project_Name/codebase/src/components/FilterList/index.tsx
> +        keyExtractor={(item) => String(item.key)}
Nesse caso precisa do String, já que a key é uma string mesmo, não teria que transformar em number?

2021-11-14 22:14 UTC, huduarte commented on Project_Name/codebase/src/components/FilterList/index.tsx
> +  setCategory: (tagKey: string) => void;
Eu decidi nomear esses valores que a gente passa para o Filter Lists de Category, nesse caso posso colocar Categories ?

2021-11-14 23:11 UTC, pedro-candido commented on Project_Name/codebase/src/components/FilterButton/index.tsx
> +  active?: boolean;
Acho que como padrão, para nomear variáveis booleanas, a gente pode adotar aquela forma: 'isActive', o que você acha?

2021-11-15 13:55 UTC, pedro-candido approved these changes

2021-11-15 14:16 UTC, ildaneta approved these changes

2021-11-15 14:16 UTC, merged