Feature/nft page
ildaneta/make-crypto-mobile-hackathon pull request #36
Opened 2021-11-17 22:00 UTC by pedro-candido

- Nft page created

2021-11-17 22:05 UTC, andersonAncilon commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    justifyContent: 'space-between',
@pedro-candido este alinhamento não foi criado no enum juntamente com o 'center'?

2021-11-17 22:05 UTC, andersonAncilon commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    // alignItems: 'flex-start',
Esse comentário será reutilizado?

2021-11-17 22:18 UTC, pedro-candido commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    // alignItems: 'flex-start',
Este não, vou subir correção

2021-11-17 22:18 UTC, pedro-candido commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    justifyContent: 'space-between',
Não foi, criarei, boa!

2021-11-17 22:25 UTC, ildaneta requested changes

2021-11-17 22:25 UTC, ildaneta commented on Project_Name/codebase/src/screens/DescriptionNft/index.tsx
> +      <ScrollView showsVerticalScrollIndicator={false} style={{ flex: 1 }}>
Pedro cria um mini estilo para esse kk

2021-11-17 22:25 UTC, ildaneta commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    height: 400,
Criar esse tamanho de height

2021-11-17 22:25 UTC, ildaneta commented on Project_Name/codebase/src/screens/DescriptionNft/styles.ts
> +    width: '100%',
Utilizar o valor de dimensions

2021-11-18 00:23 UTC, ildaneta approved these changes

2021-11-18 00:23 UTC, huduarte approved these changes

2021-11-18 00:23 UTC, merged