Feature/modal
ildaneta/make-crypto-mobile-hackathon pull request #38
Opened 2021-11-18 22:53 UTC by pedro-candido

- Modal component created
- Close svg icon
- Close button on modal made

2021-11-18 22:57 UTC, huduarte approved these changes

2021-11-19 00:03 UTC, ildaneta approved these changes

2021-11-20 01:31 UTC, ildaneta requested changes

2021-11-20 01:31 UTC, ildaneta commented on Project_Name/codebase/src/screens/ConnectWallet/styles.ts
> +    marginHorizontal: 11,
Colocar o valor de dimensions

2021-11-20 01:31 UTC, ildaneta commented on Project_Name/codebase/src/screens/ConnectWallet/styles.ts
> +    textAlign: 'center',
Utilizar o valor de AlignTypes

2021-11-20 01:31 UTC, ildaneta commented on Project_Name/codebase/src/screens/PlaceABid/styles.ts
> +    paddingHorizontal: dimensions.width19,
nesse caso a gente teria que utilizar o valor de dimensions normal sem ser o width

2021-11-20 01:31 UTC, ildaneta commented on Project_Name/codebase/src/styles/dimensions.ts
> +  width19: 19,
Não precisaríamos desse valor pelo comentário lá de cima

2021-11-21 23:25 UTC, ildaneta approved these changes

2021-11-21 23:25 UTC, huduarte approved these changes

2021-11-21 23:25 UTC, merged