feature: profile screen
ildaneta/make-crypto-mobile-hackathon pull request #39
Opened 2021-11-21 22:42 UTC by huduarte

- adding profile button component
- adding nft image component
- adding more dimensions and borders sizes
- adding clipboard lib
- adding svgs images
- adding png export type

2021-11-21 22:50 UTC, pedro-candido requested changes

2021-11-21 22:50 UTC, pedro-candido commented on Project_Name/codebase/src/components/ProfileButton/styles.ts
> +    alignItems: 'center',
Trocar por alignTypes

2021-11-21 22:50 UTC, pedro-candido commented on Project_Name/codebase/src/components/NftImage/styles.ts
> +    height: 160,
Se puder criar o estilo lá no dimensions

2021-11-22 11:48 UTC, ildaneta requested changes

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +                    paddingHorizontal: 16,
Hudson podemos colocar esses estilos no arquivos styles

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +                    paddingHorizontal: 16,
Utilizar o valor de dimensions

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    flexDirection: 'row',
Criei o roteiro dentro do alignTypes

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    flexDirection: 'row',
Usar o row de AlignTypes

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    borderRadius: 12,
Se não tiver esse valor em dimensions pode criar

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    width: 26,
Esse também

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    flexDirection: 'row',
Usar o row de AlignTypes

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    paddingBottom: 80, // todo: create 80 stack
Criar esse valor em dimensions

2021-11-22 11:48 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    marginTop: 40,
Criar valores em dimensions

2021-11-23 00:20 UTC, huduarte commented on Project_Name/codebase/src/screens/Profile/styles.ts
> +    flexDirection: 'row',
Ilda, nessa branch ainda nao tenho esses types

2021-11-23 00:21 UTC, pedro-candido approved these changes

2021-11-23 15:44 UTC, ildaneta requested changes

2021-11-23 15:44 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +import MenuSvg from '../../../assets/menu.svg';
hudson vamos utilizar aqui o path import do pedro?

2021-11-23 15:44 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +                contentContainerStyle={{
podemos colocar esses estios no arquivo de estilos

2021-11-23 15:44 UTC, ildaneta commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +                  style={{ width: '100%' }}
Esse estilo também e utilizar a variavel de dimensions

2021-11-23 22:31 UTC, huduarte commented on Project_Name/codebase/src/screens/Profile/index.tsx
> +import MenuSvg from '../../../assets/menu.svg';
O path não tem esse token para o assets

2021-11-23 22:47 UTC, ildaneta approved these changes

2021-11-23 22:47 UTC, merged