Feature/create nft
ildaneta/make-crypto-mobile-hackathon pull request #47
Opened 2021-11-25 01:16 UTC by pedro-candido

- Create NFT page created
- Loading added
- Adding image working

2021-11-25 01:50 UTC, ildaneta requested changes

2021-11-25 01:50 UTC, ildaneta commented on Project_Name/codebase/src/screens/CreateNFT/index.tsx
> +    console.log(imageSelected);
Vai ter algo aqui nesse useEffect?

2021-11-25 01:51 UTC, pedro-candido commented on Project_Name/codebase/src/screens/CreateNFT/index.tsx
> +    console.log(imageSelected);
Nop, esqueci de remover

2021-11-27 13:45 UTC, huduarte approved these changes

2021-11-27 20:11 UTC, ildaneta approved these changes

2021-11-27 20:19 UTC, merged