feat: description text created
ildaneta/make-crypto-mobile-hackathon pull request #8
Opened 2021-11-13 20:25 UTC by pedro-candido

- Description component created
- Styles for description created

2021-11-13 22:01 UTC, ildaneta requested changes

2021-11-13 22:01 UTC, ildaneta commented on Project_Name/codebase/src/components/Description/index.tsx
> +  textDescription: string;
Pedro, conforme alinhamos vamos criar props a mais para cor do texto, fonte com peso, tamanho, qual a fonte será utilizada e o alinhamento do texto.

2021-11-13 22:01 UTC, ildaneta commented on Project_Name/codebase/src/components/Description/styles.ts
> +const styles = StyleSheet.create({
Pedro, conforme alinhamos, essas propriedades não serão passadas por default mas sim por propriedades

2021-11-13 23:50 UTC, huduarte approved these changes

2021-11-14 01:00 UTC, ildaneta approved these changes

2021-11-14 01:00 UTC, merged